# Requires to build before, locally, this image (not provided on pramsey dockerhub repo. It's only used from transitiory purpose anyway
FROM pramsey/pg_featureserv:latest

USER root
RUN yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm ;\
    yum -y install postgresql14

COPY --chown=1001 ./wait-for-db.sh .
USER 1001
